version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/letsencrypt
      - /var/www:/usr/share/nginx/html
    depends_on:
      - certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email your_email@example.com --agree-tos -d your_domain.com
